#!/bin/sh

# Available environment variables:
#
# DOCKER_IMAGE_NAME
# DOCKER_IMAGE_TAG
# DOCKER_REGISTRY
# DOCKER_NAMESPACE

DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG:-jenkins-$BUILD_ID}

docker build --no-cache -t $DOCKER_IMAGE_NAME .
docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_REGISTRY/$DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
