#!/usr/bin/env bash
set -x

# Available environment variables:
#
# DOCKER_IMAGE_NAME
# DOCKER_NAMESPACE
# DOCKER_REGISTRY
# DOCKER_TAG

docker rmi -f $DOCKER_IMAGE_NAME:$DOCKER_TAG
docker rmi -f $DOCKER_REGISTRY/$DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:$DOCKER_TAG
