#!/bin/sh

# Available environment variables:
#
# DOCKER_IMAGE_NAME
# DOCKER_IMAGE_TAG
# DOCKER_REGISTRY
# DOCKER_NAMESPACE
# DOCKER_REGISTRY_USERNAME
# DOCKER_REGISTRY_PASSWORD

DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG:-jenkins-$BUILD_ID}

docker login --username $DOCKER_REGISTRY_USERNAME --password $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY
docker push  $DOCKER_REGISTRY/$DOCKER_NAMESPACE/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
